name: Release check
on:
  workflow_dispatch:
  release:
   types: [published]
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      issues: write
      actions: read
jobs:
  test-release:    
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build for deployment on branch $GITHUB_REF"
      - name: Checkout code
        uses: actions/checkout@v2    
      - name: Release check  
        run: |
            echo "done!!"
