name: Manually rollback
on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'The revision to rollback to'
        required: true

      branch:
        description: 'The branch that the rollback affects'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
#       - run: echo "Build for deployment on branch $GITHUB_REF"
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#            ref: ${{ github.event.inputs.branch }}
#            fetch-depth: 0

#       - name: Set up Java
#         uses: actions/setup-java@v2
#         with:
#           java-version: '8'
#           distribution: 'temurin'
#           cache: 'maven'
#       - name: Build with Maven
#         run: mvn clean install

#       - name: Create tag
#         uses: actions/github-script@v5
#         with:
#           script: |
#             github.rest.git.createRef({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               ref: 'refs/tags/<tagname>',
#               sha: context.sha
#             })
      - name: Rolls back to a certain version
        uses: fivebluepetals/rollback-action@v1.0
        with:
          branch: ${{ github.event.inputs.branch }}
          revision: ${{ github.event.inputs.revision }}
